"""add override prompt

Revision ID: 1071baf42771
Revises: ff86dfacb1ca
Create Date: 2025-02-18 20:28:52.605728

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "1071baf42771"
down_revision: Union[str, None] = "ff86dfacb1ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("uploader_credentials", sa.Column("override_prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("uploader_credentials", "override_prompt")
    # ### end Alembic commands ###
