"""add override username

Revision ID: 18a982f762ea
Revises: 6bec1f5f2a65
Create Date: 2025-02-23 21:32:43.006863

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "18a982f762ea"
down_revision: Union[str, None] = "6bec1f5f2a65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("uploader_credentials", sa.Column("override_username", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("uploader_credentials", "override_username")
    # ### end Alembic commands ###
