"""add override author

Revision ID: 6bec1f5f2a65
Revises: 1071baf42771
Create Date: 2025-02-19 10:07:35.551529

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "6bec1f5f2a65"
down_revision: Union[str, None] = "1071baf42771"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("uploader_credentials", sa.Column("override_author", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("uploader_credentials", "override_author")
    # ### end Alembic commands ###
