"""initial commit

Revision ID: 9d7f39385afe
Revises: 
Create Date: 2025-02-17 15:56:48.901364

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "9d7f39385afe"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aigc_contents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text_content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("image_content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("retry", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "uploader_credentials",
        sa.Column("uploader", sa.Enum("OFFIACCOUNT", name="uploaders"), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("credential", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("uploader", "username"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("uploader_credentials")
    op.drop_table("aigc_contents")
    # ### end Alembic commands ###
