name: Build Binary

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "pyproject.toml" # we consider version has been bumped

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        env:
          POETRY_VIRTUALENVS_CREATE: false
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --no-cache --no-interaction

      - name: Build Python script
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: deepseek_wechat_automation/main.py
          include-data-dir: |
            alembic=alembic
            templates=templates
          mode: app

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
          include-hidden-files: true

      - name: Release for Windows
        uses: svenstaro/upload-release-action@v2
        with:
          tag: latest
          prerelease: false
          overwrite: true
          file: build/main.exe
          asset_name: deepseek-wechat-automation-windows.exe
          release_name: deepseek-wechat-automation
